### ISSUE TITLE
not interactive cli mode

### ISSUE THREAD

**Issue by yanganto** [yanganto/s3rs#23]

**Comment by omac777** [comment]
I believe you mean in a one-shot command without s3rs-specific shell.
To clarify what I mean, for example I wish to invoke an s3rs request from a bash shell.

Possibly there could be bash-shell s3rs completion helpers created.

Here is an example. Invoke s3rs as a one-shot command without a shell:

```
s3rs --endpoint-config ~/.config/s3rs/wasabi.toml --putsrc ../blahtest.tgz --putdest s3://tests3rs/blahtest.tgz --time --progress
```

```
--endpoint-config
```
     Provide which endpoint you wish to connect to. i.e. wasabi, aws, clevercloud, google

```
--putsrc
```
     Put request.  Here is the source.  Could be a local file or a remote s3 url location as you have in your shell.

```
--putdest
```
     Put request.  Here is the destination.  Could be a local file or a remote s3 url location as you have in your shell.

```
--time
```
     Benchmark the time to accomplish this one-shot command without a shell.

```
--progress [percent|chunks|bytes]
```
     Show progress % remaining, chunks remaining, bytes remaining along with estimated time of arrival(ETA)

**Comment by yanganto** [comment]
yeh, I works on single command version and  will release soon :)

**Comment by yanganto** [comment]
Hi omac777, I know there are still a  lot  of  detail need to  be enhanced about cli. I want  close this issue first and break down other  detail into issuses.  Such that I can be focus on one feature at one time.  Your  other requests will be opened as issues latter.

**Comment by omac777** [comment]
On 9/28/19 6:53 AM, yanganto wrote:
> Hi omac777, I know there are still a  lot  of  detail need to  be enhanced about cli. I want  close this issue first and break down other  detail into issuses.  Such that I can be focus on one feature at one time.  Your  other requests will be opened as issues latter.
> 

Thank you for replying.  You're awesome.  In order to save yourself some
time, please don't feel obligated to replying all the time or to open
other issues.

Cheers :)
David Marceau
Ottawa, Ontario, Canada
613.218.7497
