### ISSUE TITLE
handle command history, and use up, down, or Ctrl + n, Ctrl + p to navigate the command history.

### ISSUE THREAD

**Issue by yanganto** [yanganto/s3rs#4]

**Comment by omac777** [comment]
To clarify, yes the shell command history would be beneficial with the CUA style up and down and the emacs style ctrl n and ctrl p.

Also please consider for editing a previous command:
ctrl d for deleting a character
ctrl a for moving cursor to beginning of line
ctrl e for going to the end of line
enabling the backspace key for removing the previous character

Also it would be agreeable to have a command history file just for s3rs.

Thank you for listening.

**Comment by yanganto** [comment]
Thanks for using it. @omac777 
I will implement a command history for s3rs. #53
