### ISSUE TITLE
Add automated releases

### ISSUE THREAD

**Issue by tombh** [yanganto/s3rs#41]
I would have given this a try if there was a static build in the Github releases here. It's free and easy enough to do with say Travis CI.

**Comment by yanganto** [comment]
Thank for your suggestion, I will implement this into CI flow.  Besides, it is always welcome to create an issue or PR that you have any idea or suggestion.

**Comment by yanganto** [comment]
@tombh I try to build with target `x86_64-unknown-linux-musl`, but there is some issue with the depending lib `openssl-sys`.  If you have experience with this,  may you give me a hand on this issue?  Thank you.

**Comment by yanganto** [comment]
@tombh 
here is the static binary build
https://drive.google.com/open?id=1hFUOCpufGID1vBBUehaSWZ2woFAihGkk

I am working on the ci flow in Travis because I am an ArchLinux user but Travis is based on Ubuntu so that I need to figure out how to set up an Ubuntu with musl environment.

**Comment by tombh** [comment]
Thanks, the binary works.

I'm confused about Travis using musl, as far as I know musl is commonly found in Alpine Linux, which is often used to create tiny Docker images. I don't see that your `.travis.yml` file has been updated here, so I can't tell how exactly you're making the build. Also you don't need to push the build to Google Drive, Github has support for build assets in its Releases, and Travis has built-in support for Github Releases: https://docs.travis-ci.com/user/deployment/releases/

There may even be tools you can use to automate the entire process, for example: https://github.com/japaric/trust I've never used it before though.

Also, I saw that `s3rs` puts its config directly in `$HOME`, I think it's good practice to put config files under `$HOME/.config/...`.

**Comment by yanganto** [comment]
@tombh Very thanks for your help.  

- I develop this #42  and I will finish this feature before Sunday night.  
- I open a new issue #43 to fix the config file problem.   

Thanks for using.  If there anything to should be enhanced, please kindly tell me.

**Comment by yanganto** [comment]
Automated releases implement.  Thanks for your suggestion.
