### ISSUE TITLE
A script mode with --script flag

### ISSUE THREAD

**Issue by omac777** [yanganto/s3rs#50]
Hats off on the great work.  I managed to:
- connect to wasabi with s3rs
- create a bucket(directory)
- put an object(file) roughly 13MB go1.13 zip file which displayed an error.
- get an object(file) but was not entirely complete 13MB go1.13 zip file, but that was expected considering upload error was displayed. It did fetch something which is progress.
- do a bucket(directory) listing which did display the contained objects(files).

One recommendation: when listing details of the bucket, I expected to see the file size as part of that listing.  It wasn't.  It would only be displayed as part of the debug log if enabled.  The heavy lifting of s3rs in your other s3handler crate.  I have been looking at dua-cli and it has options to list file sizes as Binary, Metric, Bytes, MiB, GiB, MB, etc.  It would be useful to see something similar with your tool.

I just discovered a python-based fuse driver for s3 called yas3fs:
https://github.com/danilop/yas3fs
It might serve as inspiration, but rewritten in rust.
The interesting aspect of it imho is "Parallel multi-part uploads".

Here is another golang-based fuse driver for s3 that might also be inspirational:
https://github.com/kahing/goofys

Cheers.

**Comment by yanganto** [comment]
Very Very thanks for your suggestion.  I already fix multipart bugs and the listing detail and parallel multipart will come in these days.  Thanks.

**Comment by omac777** [comment]
For your information, I have attached a file I attempted to upload to wasabi.  It's actually the go1.13 tgz I downloaded recently, but renamed to blahtest.tgz
```
-rw-r--r--. 1 davidm davidm 120050424 Sep 24 10:48 blahtest.tgz
-rw-rw-r--. 1 davidm davidm 120050424 Sep 20 11:07 go1.13.linux-amd64.tar.gz
```

Please note the file size to upload in the trace log does mention 120050424 bytes, but after uploading is complete, I did an ls on that file on wasabi and it lists it as being 120586240 bytes.

```
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>gmac</Name><Prefix>tests3rs/blahtest.tgz</Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>tests3rs/blahtest.tgz</Key><LastModified>2019-09-24T14:50:40.000Z</LastModified><ETag>&quot;86755c9deba75e22ef6897ecb5514264-23&quot;</ETag><Size>120586240</Size><Owner><ID>2E80E1494A259B47E615EC7135664324D70D65CF502AC6FFB134E954ABAFF4F2</ID><DisplayName>ottawasupport</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
```


[mys3rsLogTraceUploadWasabi.txt](https://github.com/yanganto/s3rs/files/3647913/mys3rsLogTraceUploadWasabi.txt)

One other last recommendation related to this:  Within the put command, please display the exact number of bytes uploaded that matches the source file size hopefully once completed to reassure the s3rs users the file did arrive at its destination completely.  Are there checksum options on the amazon side to enable i.e. sha256sum?  To reassure the user, it would be desirable to display both the source-file sha256sum and destination-file sha256sum and reassuring they do in fact match.
I know it's beyond the scope of the tool since it should only be client-side, but it would have been nice.

**Comment by yanganto** [comment]
AWS uses md5sum for etag in a single upload.  However, multipart upload is not md5sum. Here is the description of etag of multipart.

```
After a successful complete request, the parts no longer exist. Your complete multipart upload request must include the upload ID and a list of both part numbers and corresponding ETag values. Amazon S3 response includes an ETag that uniquely identifies the combined object data. This ETag will not necessarily be an MD5 hash of the object data.
```

In your test file, the etag after complete is `86755c9deba75e22ef6897ecb5514264-23`
the `-23` means the object uploaded by 23 multiple parts. but `86755c9deba75e22ef6897ecb5514264` is not the md5sum of `blahtest.tgz`.(maybe you can help me to double check on this) 

I think there is no way to check the md5sum of the server object multipart uploaded.  
However, if you really want to check the object check md5sum on the server, I can provide a command to upload file in a single request without multipart. 

The largest object that can be uploaded in a single PUT is 5 gigabytes. So the object small than 5 gigabytes can be uploaded without multipart, such that checking md5sum can be implemented.  But the trade-off is that this upload can not be parallel in the future.

**Comment by yanganto** [comment]
Maybe the command name can be `sput` or something short and easy to comprehend. May you help with this naming?

**Comment by omac777** [comment]
I don't think anyone will be interested in a "single PUT" with a 5GB MAX Capacity.
I think it best to to continue with your multi-part upload tool, but it would have been nice to send commands to your tool via input script, but that requires extra CLI command line arguments.
I am just one single user of your tool, but I prefer CLI tools with many arguments for which everything is configurable from the cli invocation itself.  For inspiration I believe the ftp cli was correct.  It is a shell also, but allowed for passing ftp scripts within the cli to automate everything connection/put/get/etc...
```
@echo off
echo open 192.168.100.101> ftpgetscript.txt
echo user1>> ftpgetscript.txt
echo demo>> ftpgetscript.txt
echo get %1>> ftpgetscript.txt
echo quit>> ftpgetscript.txt
ftp -s:ftpgetscript.txt
```

something like this is interesting.
You could invoke an endpoint config file within the script like so:
```
echo endpointconfig /home/davidm/config/wasabi.conf > s3rsPutScript.txt
echo put /home/davidm/Download/blahtest.tgz s3://gmac/tests3rs/blahtest.tgz >> s3rsPutScript.txt
echo ls s3://gmac/tests3rs/blahtest.tgz >> s3rsPutScript.txt
echo exit >> s3rsPutScript.txt
```
```
s3rs --script s3rsPutScript.txt
```



Thank you for listening by the way.

**Comment by yanganto** [comment]
This is a good idea.  I will think about how to implement this.

**Comment by yanganto** [comment]
Already implemented with `--config` option

`s3rs -c, --config <S3RS CONFIGURE> <CMD>`
